# Generated by Django 5.1.7 on 2025-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FioCurr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=3, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=3, max_digits=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
