# Generated by Django 5.1.7 on 2025-03-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchingdata", "0002_cryptocurrency_price_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
                (
                    "marketpriceUSD",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=20),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="price_history",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="fetchingdata.coin",
            ),
        ),
        migrations.DeleteModel(
            name="CryptoCurrency",
        ),
    ]
