# Generated by Django 5.1.7 on 2025-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchingdata", "0003_coin_alter_price_history_asset_delete_cryptocurrency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
