# Generated by Django 5.1.7 on 2025-03-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetchingdata", "0004_alter_coin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="marketpriceUSD",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
