# Generated by Django 5.1.7 on 2025-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fetchingdata", "0006_portfolio_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiocurr",
            name="name",
        ),
        migrations.RemoveField(
            model_name="fiocurr",
            name="volume",
        ),
    ]
