from django.core.management.base import BaseCommand
from base.models import Coin

class Command(BaseCommand):

    def handle(self, *args, **kwargs):
        crypto_data = {
            "bitcoin": {"symbol": "BTC", "name": "Bitcoin"},
            "ethereum": {"symbol": "ETH", "name": "Ethereum"},
            "tether": {"symbol": "USDT", "name": "Tether"},
            "binancecoin": {"symbol": "BNB", "name": "Binance Coin"},
            "solana": {"symbol": "SOL", "name": "Solana"},
            "ripple": {"symbol": "XRP", "name": "XRP"},
            "usd-coin": {"symbol": "USDC", "name": "USD Coin"},
            "cardano": {"symbol": "ADA", "name": "Cardano"},
            "dogecoin": {"symbol": "DOGE", "name": "Dogecoin"},
            "avalanche-2": {"symbol": "AVAX", "name": "Avalanche"},
            "shiba-inu": {"symbol": "SHIB", "name": "Shiba Inu"},
            "polkadot": {"symbol": "DOT", "name": "Polkadot"},
            "tron": {"symbol": "TRX", "name": "TRON"},
            "chainlink": {"symbol": "LINK", "name": "Chainlink"},
            "polygon-pos": {"symbol": "MATIC", "name": "Polygon"},
            "wrapped-bitcoin": {"symbol": "WBTC", "name": "Wrapped Bitcoin"},
            "bitcoin-cash": {"symbol": "BCH", "name": "Bitcoin Cash"},
            "uniswap": {"symbol": "UNI", "name": "Uniswap"},
            "litecoin": {"symbol": "LTC", "name": "Litecoin"},
            "internet-computer": {"symbol": "ICP", "name": "Internet Computer"},
            "dai": {"symbol": "DAI", "name": "Dai"},
            "ethereum-classic": {"symbol": "ETC", "name": "Ethereum Classic"},
            "stellar": {"symbol": "XLM", "name": "Stellar"},
            "cosmos": {"symbol": "ATOM", "name": "Cosmos"},
            "okb": {"symbol": "OKB", "name": "OKB"},
            "monero": {"symbol": "XMR", "name": "Monero"},
            "filecoin": {"symbol": "FIL", "name": "Filecoin"},
            "aptos": {"symbol": "APT", "name": "Aptos"},
            "hedera-hashgraph": {"symbol": "HBAR", "name": "Hedera Hashgraph"},
            "crypto-com-chain": {"symbol": "CRO", "name": "Cronos"},
            "arbitrum": {"symbol": "ARB", "name": "Arbitrum"},
            "near": {"symbol": "NEAR", "name": "NEAR Protocol"},
            "vechain": {"symbol": "VET", "name": "VeChain"},
            "stacks": {"symbol": "STX", "name": "Stacks"},
            "mantle": {"symbol": "MNT", "name": "Mantle"},
            "quant-network": {"symbol": "QNT", "name": "Quant"},
            "maker": {"symbol": "MKR", "name": "Maker"},
            "the-graph": {"symbol": "GRT", "name": "The Graph"},
            "lido-dao": {"symbol": "LDO", "name": "Lido DAO"},
            "optimism": {"symbol": "OP", "name": "Optimism"},
            "aave": {"symbol": "AAVE", "name": "Aave"},
            "render-token": {"symbol": "RNDR", "name": "Render Token"},
            "injective-protocol": {"symbol": "INJ", "name": "Injective Protocol"},
            "algorand": {"symbol": "ALGO", "name": "Algorand"},
            "thorchain": {"symbol": "RUNE", "name": "THORChain"},
            "immutable-x": {"symbol": "IMX", "name": "Immutable X"},
            "bittensor": {"symbol": "TAO", "name": "Bittensor"},
            "bitcoin-cash-sv": {"symbol": "BSV", "name": "Bitcoin SV"},
            "kaspa": {"symbol": "KAS", "name": "Kaspa"},
            "celestia": {"symbol": "TIA", "name": "Celestia"},
            "fantom": {"symbol": "FTM", "name": "Fantom"},
            "gala": {"symbol": "GALA", "name": "Gala"},
            "flow": {"symbol": "FLOW", "name": "Flow"},
            "axie-infinity": {"symbol": "AXS", "name": "Axie Infinity"},
            "theta-token": {"symbol": "THETA", "name": "Theta Network"},
            "arweave": {"symbol": "AR", "name": "Arweave"},
            "tezos": {"symbol": "XTZ", "name": "Tezos"},
            "fetch-ai": {"symbol": "FET", "name": "Fetch.ai"},
            "rocket-pool-eth": {"symbol": "RETH", "name": "Rocket Pool ETH"},
            "first-digital-usd": {"symbol": "FDUSD", "name": "First Digital USD"},
            "whitebit": {"symbol": "WBT", "name": "WhiteBIT Coin"},
            "singularitynet": {"symbol": "AGIX", "name": "SingularityNET"},
            "bonk": {"symbol": "BONK", "name": "Bonk"},
            "conflux-token": {"symbol": "CFX", "name": "Conflux"},
            "kucoin-token": {"symbol": "KCS", "name": "KuCoin Token"},
            "neo": {"symbol": "NEO", "name": "Neo"},
            "mina-protocol": {"symbol": "MINA", "name": "Mina Protocol"},
            "chiliz": {"symbol": "CHZ", "name": "Chiliz"},
            "gatechain-token": {"symbol": "GT", "name": "GateToken"},
            "pepe": {"symbol": "PEPE", "name": "Pepe"},
            "marinade-staked-sol": {"symbol": "MSOL", "name": "Marinade staked SOL"},
            "akash-network": {"symbol": "AKT", "name": "Akash Network"},
            "gnosis": {"symbol": "GNO", "name": "Gnosis"},
            "tokenize-xchange": {"symbol": "TKX", "name": "Tokenize Xchange"},
            "dydx": {"symbol": "DYDX", "name": "dYdX"},
            "synthetix-network-token": {"symbol": "SNX", "name": "Synthetix"},
            "eos": {"symbol": "EOS", "name": "EOS"},
            "pancakeswap-token": {"symbol": "CAKE", "name": "PancakeSwap"},
            "klay-token": {"symbol": "KLAY", "name": "Klaytn"},
            "terra-luna": {"symbol": "LUNC", "name": "Terra Classic"},
            "oasis-network": {"symbol": "ROSE", "name": "Oasis Network"},
            "curve-dao-token": {"symbol": "CRV", "name": "Curve DAO Token"},
            "kava": {"symbol": "KAVA", "name": "Kava"},
            "iota": {"symbol": "IOTA", "name": "IOTA"},
            "osmosis": {"symbol": "OSMO", "name": "Osmosis"},
            "compound-governance-token": {"symbol": "COMP", "name": "Compound"},
            "nexo": {"symbol": "NEXO", "name": "Nexo"},
            "wemix-token": {"symbol": "WEMIX", "name": "WEMIX Token"},
            "gmx": {"symbol": "GMX", "name": "GMX"},
            "decentraland": {"symbol": "MANA", "name": "Decentraland"},
            "radix": {"symbol": "XRD", "name": "Radix"},
            "1inch": {"symbol": "1INCH", "name": "1inch Network"},
            "enjincoin": {"symbol": "ENJ", "name": "Enjin Coin"},
            "zilliqa": {"symbol": "ZIL", "name": "Zilliqa"},
            "icon": {"symbol": "ICX", "name": "ICON"},
            "loopring": {"symbol": "LRC", "name": "Loopring"},
            "waves": {"symbol": "WAVES", "name": "Waves"},
            "xdce-crowd-sale": {"symbol": "XDC", "name": "XDC Network"},
            "ankr": {"symbol": "ANKR", "name": "Ankr"},
            "0x": {"symbol": "ZRX", "name": "0x Protocol"},
            "dexe": {"symbol": "DEXE", "name": "DeXe"},
            "sushi": {"symbol": "SUSHI", "name": "SushiSwap"},
            "woo-network": {"symbol": "WOO", "name": "WOO Network"},
            "golem": {"symbol": "GLM", "name": "Golem"}
        }

        for crypto_id, data in crypto_data.items():
            coin, created = Coin.objects.update_or_create(
                id=crypto_id,
                defaults={
                    'symbol': data['symbol'],
                    'name': data['name'],
                }
            )
            
            if created:
                self.stdout.write(self.style.SUCCESS(f"Vytvořeno: {data['name']} ({data['symbol']})"))
            else:
                self.stdout.write(self.style.WARNING(f"Existuje: {data['name']} ({data['symbol']})"))