# Generated by Django 5.2 on 2025-05-15 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CZK', 'CZK'), ('PLN', 'PLN')], default='USD', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceUSD', models.DecimalField(decimal_places=3, max_digits=20)),
                ('priceEUR', models.DecimalField(decimal_places=3, max_digits=20)),
                ('priceCZK', models.DecimalField(decimal_places=3, max_digits=20)),
                ('priceGBP', models.DecimalField(decimal_places=3, max_digits=20)),
                ('pricePLN', models.DecimalField(decimal_places=3, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='base.coin')),
            ],
            options={
                'verbose_name': 'Price history entry',
                'verbose_name_plural': 'Price history',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('marketprice', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='base.coin')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='base.portfolio')),
            ],
        ),
    ]
