# Generated by Django 5.2 on 2025-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Price_history",
            new_name="PriceHistory",
        ),
        migrations.DeleteModel(
            name="FiatCurr",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SELL", "Sell")], default="BUY", max_length=4
            ),
        ),
    ]
