# Generated by Django 5.2 on 2025-05-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='marketprice',
        ),
    ]
