# Generated by Django 5.2 on 2025-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_price_history_pricehistory_delete_fiatcurr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
