# Generated by Django 5.2 on 2025-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_pricehistory_priceczk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
