# Generated by Django 5.2 on 2025-05-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_transaction_amount_alter_transaction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='timestamp',
            new_name='created',
        ),
    ]
