# Generated by Django 5.2 on 2025-06-17 16:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_transaction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='free_funds',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=20),
        ),
    ]
