# Generated by Django 5.2 on 2025-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_portfolio_free_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='priceCZK',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='priceEUR',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='priceGBP',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='pricePLN',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='priceUSD',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
