# Generated by Django 5.2 on 2025-06-19 15:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_pricehistory_priceczk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='invested_funds',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=20),
        ),
    ]
