# Generated by Django 5.2 on 2025-06-21 10:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_portfolio_invested_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initial_amount',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=60),
        ),
    ]
