# Generated by Django 5.2 on 2025-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_transaction_initial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closed_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=60, null=True),
        ),
    ]
