# Generated by Django 5.2 on 2025-06-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_transaction_closed_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='invested_funds',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
