# Generated by Django 5.2 on 2025-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_portfolio_invested_funds_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['created'], name='base_priceh_created_e74858_idx'),
        ),
    ]
