# Generated by Django 5.2 on 2025-06-23 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_pricehistory_base_priceh_created_e74858_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_invested',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=20),
        ),
    ]
